<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZucchiLayout\Module'                     => __DIR__ . '//Module.php',
    'ZucchiLayout\Event\LayoutListener'       => __DIR__ . '//src/ZucchiLayout/Event/LayoutListener.php',
    'ZucchiLayout\Entity\Schedule'            => __DIR__ . '//src/ZucchiLayout/Entity/Schedule.php',
    'ZucchiLayout\Entity\Author'              => __DIR__ . '//src/ZucchiLayout/Entity/Author.php',
    'ZucchiLayout\Entity\Layout'              => __DIR__ . '//src/ZucchiLayout/Entity/Layout.php',
    'ZucchiLayout\Entity\Keyword'             => __DIR__ . '//src/ZucchiLayout/Entity/Keyword.php',
    'ZucchiLayout\Controller\AdminController' => __DIR__ . '//src/ZucchiLayout/Controller/AdminController.php',
    'ZucchiLayout\Service\LayoutService'      => __DIR__ . '//src/ZucchiLayout/Service/LayoutService.php',
    'ZucchiLayout\Service\Layout'             => __DIR__ . '//src/ZucchiLayout/Service/Layout.php',
    'ZucchiLayout\Validator\Layout'           => __DIR__ . '//src/ZucchiLayout/Validator/Layout.php',
    'ZucchiLayout\Options\LayoutOptions'      => __DIR__ . '//src/ZucchiLayout/Options/LayoutOptions.php',
    'ZucchiLayout\Filter\Layout'              => __DIR__ . '//src/ZucchiLayout/Filter/Layout.php',
    'ZucchiLayout\Form\Install'               => __DIR__ . '//src/ZucchiLayout/Form/Install.php',
);