<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    // definition of PEAR libraries
    'Archive_Tar' => 'Archive/Tar.php',

    'ZucchiLayout\Module'                        => __DIR__ . '/Module.php',
    'ZucchiLayout\Controller\AdminController' => __DIR__ . '/src/ZucchiLayout/Controller/AdminController.php',
    'ZucchiLayout\Event\LayoutListener' => __DIR__ . '/src/ZucchiLayout/Event/LayoutListener.php',
);